#PBS -A UQ-SCI-Earth
#PBS -l select=1:ncpus=1:mem=4GB
#PBS -l walltime=00:10:00
#PBS -e OE/
#PBS -o OE/

shopt -s expand_aliases

# old way
# cat /RDS/Q0931/10_Airbnb_SEIFA_hpc.R | tr -d '\r' > $TMPDIR/10_Airbnb_SEIFA_hpc.R

module purge
module load r+inla/20180712

cd $PBS_O_WORKDIR

rinla-exec /home/uqdgree5/Clients/uqrpancz/demo.exec

# Move the output file back to collection storage
mv m1.rds /RDS/Q0931/res/INLA/00